{
 "title": "Testnet P&L Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Sequencer Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  balance / 1000000000000000000\nFROM\n  funds\nWHERE\n  name = 'Sequencer'\n  and environment = 'ten.sepolia'\n  AND balance IS NOT NULL\nORDER BY\n  time DESC;\n"
    }
   ]
  },
  {
   "title": "GasPayment Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  balance / 1000000000000000000\nFROM\n  funds\nWHERE\n  name = 'GasPayment'\n  and environment = 'ten.sepolia'\n  AND balance IS NOT NULL\nORDER BY\n  time DESC;\n"
    }
   ]
  },
  {
   "title": "Profit and Loss (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  seq_diff as Sequencer,\n  gas_diff as GasPayment,\n  pandl as ProfitAndLoss\nFROM\n  pandl\nWHERE\n  environment = 'ten.sepolia'\nORDER BY\n  time DESC;\n"
    }
   ]
  }
 ]
}