{
 "title": "Testnet Funds",
 "tags": [
  "e2e-tests",
  "health"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "select distinct(environment) from funds;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "## Account Funds and Overall Profit And Loss"
   }
  },
  {
   "title": "Faucet Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  balance / 1000000000000000000\nFROM\n  funds\nWHERE\n  name = 'Faucet'\n  and environment = '${environment}'\n  AND balance IS NOT NULL\nORDER BY\n  time DESC;\n"
    }
   ]
  },
  {
   "title": "Sequencer Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 2 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  balance / 1000000000000000000\nFROM\n  funds\nWHERE\n  name = 'Sequencer'\n  and environment = '${environment}'\n  AND balance IS NOT NULL\nORDER BY\n  time DESC;\n"
    }
   ]
  },
  {
   "title": "GasPayment Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 14, "y": 2 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  balance / 1000000000000000000\nFROM\n  funds\nWHERE\n  name = 'GasPayment'\n  and environment = '${environment}'\n  AND balance IS NOT NULL\nORDER BY\n  time DESC;\n"
    }
   ]
  },
  {
   "title": "Profit and Loss (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  time, \n  seq_diff as sequencer,\n  gas_diff as gas_payment,\n  pandl as profit_and_loss\nFROM\n  pandl\nWHERE\n  environment = '${environment}'\nORDER BY\n  time DESC;\n"
    }
   ]
  }
 ]
}