{
 "title": "Testnet Costs",
 "tags": [
  "e2e-tests",
  "health"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "SELECT distinct environment from tx_costs;"
   },
   {
    "name": "interaction",
    "query": "select distinct name from tx_costs; "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "## Transaction Costs On Various Networks "
   }
  },
  {
   "title": "Gas Used For Contract Deployment (${environment})",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n    time,\n    MAX(CASE WHEN name = 'Storage.deploy' THEN gasused END) AS storage_deploy,\n    MAX(CASE WHEN name = 'KeyStorage.deploy' THEN gasused END) AS keystorage_deploy,\n    MAX(CASE WHEN name = 'Game.deploy' THEN gasused END) AS game_deploy,\n    MAX(CASE WHEN name = 'Calldata.deploy' THEN gasused END) AS calldata_deploy\nFROM tx_costs\nWHERE environment='${environment}'\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Gas Used For Contract Interaction (${environment})",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n    time,\n    MAX(CASE WHEN name = 'Storage.store' THEN gasused END) AS storage_store,\n    MAX(CASE WHEN name = 'KeyStorage.storeItem' THEN gasused END) AS keystorage_storeItem,\n    MAX(CASE WHEN name = 'KeyStorage.setItem' THEN gasused END) AS keystorage_setItem,\n    MAX(CASE WHEN name = 'Game.guess' THEN gasused END) AS game_guess,\n    MAX(CASE WHEN name = 'CallData.processLargeData' THEN gasused END) AS calldata_processLargeData,\n    MAX(CASE WHEN name = 'Native.transfer' THEN gasused END) AS native_transfer\nFROM tx_costs\nWHERE environment='${environment}'\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "L1 and L2 Gas Prices GWEI (${environment})",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 5, "x": 16, "y": 2 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select time, (l1gasprice/1e9) AS l1_Gas_price, (l2gasprice/1e9) AS l2_Gas_price from gas_prices where environment='${environment}'; "
    }
   ]
  },
  {
   "title": "Estimate vs Used for  ${interaction} (${environment})",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select time, gasestimate AS gas_estimate, gasused AS gas_used from tx_costs where name='${interaction}' and environment='${environment}'; "
    }
   ]
  },
  {
   "title": "USD Cost comparison all networks  ${interaction}",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    t.time, \n    (t.gasprice * t.gasused * r.rate / 1e18) AS ten_sepolia\nFROM \n    tx_costs t\nJOIN \n    (SELECT rate FROM rates WHERE currency = 'USD' ORDER BY time DESC LIMIT 1) r\nON 1=1 -- cross join\nWHERE \n    t.name = '${interaction}' \n    AND t.environment = 'ten.sepolia';"
    },
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    t.time, \n    (t.gasprice * t.gasused * r.rate / 1e18) AS ten_uat\nFROM \n    tx_costs t\nJOIN \n    (SELECT rate FROM rates WHERE currency = 'USD' ORDER BY time DESC LIMIT 1) r\nON 1=1 -- cross join\nWHERE \n    t.name = '${interaction}' \n    AND t.environment = 'ten.uat';"
    },
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    t.time, \n    (t.gasprice * t.gasused * r.rate / 1e18) AS arbitrum_sepolia\nFROM \n    tx_costs t\nJOIN \n    (SELECT rate FROM rates WHERE currency = 'USD' ORDER BY time DESC LIMIT 1) r\nON 1=1 -- cross join\nWHERE \n    t.name = '${interaction}' \n    AND t.environment = 'arbitrum.sepolia';"
    },
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    t.time, \n    (t.gasprice * t.gasused * r.rate / 1e18) AS optimism_sepolia\nFROM \n    tx_costs t\nJOIN \n    (SELECT rate FROM rates WHERE currency = 'USD' ORDER BY time DESC LIMIT 1) r\nON 1=1 -- cross join\nWHERE \n    t.name = '${interaction}' \n    AND t.environment = 'optimism.sepolia';"
    }
   ]
  },
  {
   "title": "L1 Blob Price GWEI (${environment})",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 5, "x": 16, "y": 17 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select time, (l1blobprice/1e9) AS l1_Blob_price from gas_prices where environment='${environment}'; "
    }
   ]
  }
 ]
}