name: Allocate funds to user
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: testnet
        options:
          - testnet
          - dev-testnet
      account_address:
        description: 'Account address of user'
        required: true


jobs:
  Run-Allocation:
    runs-on: self-hosted
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event running on branch ${{ github.ref }} "

      - name: Check out obscuro-test
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: Check out go-obscuro code
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: Build artifacts
        run: |
          cd ${{ github.workspace }}/go-obscuro/tools/walletextension/main
          go build -o ${{ github.workspace }}/obscuro-test/artifacts/wallet_extension/wallet_extension
          ls -l ${{ github.workspace }}/obscuro-test/artifacts

      - name: Run allocation on Obscuro testnet
        if: ${{ github.event.inputs.environment == 'testnet' }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -XUSER='${{ github.event.inputs.account_address}}' fund_users

      - name: Run allocation on Obscuro dev-testnet
        if: ${{ github.event.inputs.environment == 'dev-testnet' }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -XUSER='${{ github.event.inputs.account_address}}' -m obscuro.dev fund_users

      - name: Upload testcase output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/obscuro-test/**/Output
          retention-days: 2