# Check key balances on Sepolia.
#
name: Check sepolia transfers
on:
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, SystemTestRunner2]
    steps:
      - name: 'Check out obscuro-test'
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: 'Run transfers check'
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -m sepolia check_transfers
