# Run a set of sanity tests on uat-testnet to ensure it is up and running. The workflow is run either manually from
# a workflow dispatch, or every 30 mins.
#
name: '[Monitor] Check uat-testnet health'
run-name: Check uat-testnet health
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: 'The release version of uat-testnet'
        required: true
        default: main
        options:
          - main
          - releases/v0.20
          - releases/v0.19
          - releases/v0.18

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, ten-test-gh-runner-02]
    steps:
      - name: Set the variables
        env:
          DEFAULT_VERSION: 'main'
        run: echo "VERSION=${{ github.event.inputs.release || env.DEFAULT_VERSION }}" >> $GITHUB_ENV

      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test
          ref: ${{env.VERSION}}

      - name: 'Check out go-ten code'
        uses: actions/checkout@v3
        with:
          repository: ten-protocol/go-ten
          path: ./go-ten
          ref: ${{env.VERSION}}

      - name: 'Build required artifacts for running tests'
        run: |
          cd ${{ github.workspace }}/ten-test
          ./get_artifacts.sh
          ls -l ${{ github.workspace }}/ten-test/artifacts   

      - name: 'Run health check tests'
        run: |
          cd ${{ github.workspace }}/ten-test/tests
          /usr/local/bin/pysys.py run -m ten.uat -i health -XDURATION=0

      - name: 'Upload testcase output'
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/ten-test/**/Output
            !${{ github.workspace }}/ten-test/**/node_modules
          retention-days: 1

      - name: 'Discord notification on failure'
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.UAT_TESTNET_HEALTH_WEBHOOK }}
          title: "UAT-testnet health check tests failed"
          description: "UAT-testnet health check"
          content: "Please investigate"
          avatar_url: ${{ secrets.AVATAR_URL }}