# Check key balances on Sepolia.
#
name: Check sepolia transfers
on:
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, ten-test-gh-runner-02]
    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Run transfers check'
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m sepolia check_transfers
