# Check key balances on Sepolia to determine profits
#
name: '[Monitor] Check sepolia-testnet profits'
run-name: Check sepolia-testnet profits
on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, ten-test-gh-runner-02]
    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Run funds check'
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.sepolia check_profits
