# Print a set of test details
#
name: '[execute] Execute print tests'
run-name: Print test details
on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Arguments (--help for usage)'
        required: true
        default: '-a auto'

jobs:
  test-run:
    runs-on: [self-hosted, Linux, X64, all-testnets]
    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Print tests'
        run: |
          cd ${{ github.workspace }}/ten-test
          /usr/local/bin/pysys.py print ${{ github.event.inputs.arguments }}

