# Run a set of sanity tests on sepolia-testnet to ensure it is up and running
#
name: '[inspect] Check sepolia health'
run-name: Check sepolia-testnet health
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, all-testnets]
    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Check out go-ten code'
        uses: actions/checkout@v3
        with:
          repository: ten-protocol/go-ten
          path: ./go-ten
          ref: 'releases/v1.0'

      - name: 'Build required artifacts for running tests'
        run: |
          cd ${{ github.workspace }}/ten-test
          ./get_artifacts.sh
          ls -l ${{ github.workspace }}/ten-test/artifacts   

      - name: 'Run health check tests (primary gateway)'
        run: |
          cd ${{ github.workspace }}/ten-test
          /usr/local/bin/pysys.py run -r -m ten.sepolia -i health -XITERATIONS_FULL=0 -XRUN_TYPE=health 

      - name: 'Alert for primary gateway'
        if: always()
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.sepolia -XRUN_TYPE=health -XRUN_NAME=Primary_gateway_health -XRUN_URL=$RUN_URL -XNO_CONNECT alert_support

      - name: 'Run health check tests (dexynth gateway)'
        if: always()
        run: |
          sleep 5 
          cd ${{ github.workspace }}/ten-test/tests
          PRIMARY_HOST_HTTP=https://rpc.dexynth-gateway.ten.xyz PRIMARY_HOST_WS=wss://rpc.dexynth-gateway.ten.xyz /usr/local/bin/pysys.py run -r -m ten.sepolia -o dexynth -XRUN_TYPE=health-dexynth gen_cor_040 gen_cor_073 gen_cor_106

      - name: 'Alert for dexynth gateway'
        if: always()
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.sepolia -XRUN_TYPE=health-dexynth -XRUN_NAME=Dexynth_gateway_health -XRUN_URL=$RUN_URL -XNO_CONNECT alert_support

      - name: 'Upload testcase output'
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/ten-test/**/Output
            !${{ github.workspace }}/ten-test/**/node_modules
          retention-days: 1

      - name: 'Discord notification on failure'
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.TESTNET_HEALTH_WEBHOOK }}
          title: "The health_check_sepolia.yml workflow has failed"
          description: "The workflow shows failures and requires investigation"
          content: "For information <@814873419207409685>"
          avatar_url: ${{ secrets.AVATAR_URL }}