# Check key balances on mainnet
#
name: '[inspect] Check mainnet funds'
run-name: Check mainnet funds
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, all-testnets]
    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Check out go-ten code'
        uses: actions/checkout@v3
        with:
          repository: ten-protocol/go-ten
          path: ./go-ten
          ref: 'releases/v1.3'

      - name: 'Build required artifacts for running tests'
        run: |
          cd ${{ github.workspace }}/ten-test
          ./get_artifacts.sh
          ls -l ${{ github.workspace }}/ten-test/artifacts  

      - name: 'Run funds check'
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -r -m ten.mainnet -XRUN_TYPE=funds check_funds

      - name: 'Alert on funds check'
        if: always()
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.mainnet -XRUN_TYPE=funds -XRUN_NAME=Funds_health -XRUN_URL=$RUN_URL -XNO_CONNECT alert_support

      - name: 'Discord notification on failure'
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.WORKFLOW_STATUS_WEBHOOK }}
          title: "The health_check_mainnet_funds.yml workflow has failed"
          description: "The workflow shows failures and requires investigation"
          content: "For information <@814873419207409685>"




