# Performs any clean up or health checks on the VM runner 02
#
name: '[system] Clean docker gh-runner-01'
run-name: Cleaning runner 01 (${{ github.event_name }})
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, ten-test-gh-runner-01]
    steps:
      - name: 'Clean the docker folder'
        run: |
          sudo systemctl stop docker
          sudo rm -rf /var/lib/docker/
          sudo systemctl start docker

