# Perform clean up or health checks on the VM runner 03
#
name: '[system] Clean gh-runner-03'
run-name: Cleaning runner 04 (${{ github.event_name }})
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, local-testnets]
    steps:
      - name: 'Clean the docker folder'
        run: |
          sudo systemctl stop docker
          sudo rm -rf /var/lib/docker/
          sudo systemctl start docker

