# Reset the nonce persistence on sepolia-testnet
#
name: '[system] Reset db gh-runner-04'
run-name: Reset persistence on gh-runner-04
on:
  workflow_dispatch:

jobs:
  reset-persistence:
    runs-on: [self-hosted, Linux, X64, ten-test-gh-runner-04]
    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Check out go-ten code'
        uses: actions/checkout@v3
        with:
          repository: ten-protocol/go-ten
          path: ./go-ten

      - name: 'Build artifacts'
        run: |
          cd ${{ github.workspace }}/go-ten/tools/walletextension/main
          go build -o ${{ github.workspace }}/ten-test/artifacts/wallet_extension/wallet_extension
          ls -l ${{ github.workspace }}/ten-test/artifacts

      - name: 'Persistence reset dev'
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.dev persistence_reset

      - name: 'Persistence reset uat'
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.uat persistence_reset

      - name: 'Persistence reset sepolia'
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.sepolia persistence_reset

      - name: 'Persistence reset arbitrum sepolia'
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m arbitrum.sepolia persistence_reset

      - name: 'Persistence reset optimism sepolia'
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m optimism.sepolia persistence_reset
          
      - name: 'Upload output'
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/ten-test/**/Output
            !${{ github.workspace }}/ten-test/**/node_modules
          retention-days: 1