# Test the alerting mechanisms based on a run type and name
#
name: '[system] Test alerting'
run-name: Test alerting
on:
  workflow_dispatch:
    inputs:
      run_type:
        description: 'The type of the alerting run'
        required: true
        default: 'test'
      run_name:
        description: 'The name of the alerting run'
        required: true
        default: 'Test_alert'

jobs:
  run-test-alerts:
    runs-on: [self-hosted, Linux, X64, all-testnets]
    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: 'Check out ten-test'
        uses: actions/checkout@v3
        with:
          path: ./ten-test

      - name: 'Run the alert checking'
        if: always()
        run: |
          cd ${{ github.workspace }}/ten-test/admin
          /usr/local/bin/pysys.py run -m ten.sepolia -XRUN_TYPE=${{ github.event.inputs.run_type }} -XRUN_NAME=${{ github.event.inputs.run_name }} -XRUN_URL=$RUN_URL -XNO_CONNECT alert_support

      - name: 'Discord notification on success'
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.TESTNET_HEALTH_WEBHOOK }}
          title: "The system_test_alerts.yml workflow has passed"
          description: "The workflow passed and no investigation required"
          content: "For information <@814873419207409685>"

      - name: 'Discord notification on failure'
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.TESTNET_HEALTH_WEBHOOK }}
          title: "The system_test_alerts.yml workflow has failed"
          description: "The workflow shows failures and requires investigation"
          content: "For information <@814873419207409685>"